<?php
namespace Wsdl2PhpGenerator\Filter;

use Wsdl2PhpGenerator\Service;
use Wsdl2PhpGenerator\Type;

/**
 * Allow to filter classes that will be generated by generator.
 * @see Wsdl2PhpGenerator\Generator
 */
interface FilterInterface
{
    /**
     * @param Service $service
     * @return Service
     */
    public function filter($service);
}