<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../cli/CliParser.php';

/**
 * Test class for CliParser.
 * Generated by PHPUnit on 2009-10-24 at 17:53:15.
 */
class CliParserTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var CliParser
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new CliParser;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   *
   */
  public function testParse()
  {
    $arr = array('-a', '-b=foo', '-c bar', '--export', '--foo=bar', '-xyz', '-=asd', 'bluff', 'inva--lid');
    $this->object->parse($arr);

    $this->assertTrue($this->object->flag('a'));
    $this->assertEquals('foo', $this->object->flag('b'));
    $this->assertEquals('bar', $this->object->flag('c'));
    $this->assertTrue($this->object->flag('export'));
    $this->assertEquals('bar', $this->object->flag('foo'));
    $this->assertTrue($this->object->flag('x'));
    $this->assertTrue($this->object->flag('y'));
    $this->assertTrue($this->object->flag('z'));
  }
}
?>
