filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/generated/*'

build:
    dependencies:
        override:
            -
              command: 'yes | pecl install soap'
              not_if: 'php -r "exit(extension_loaded(''soap'') ? 0 : 1);"'
            - 'composer install --dev --no-interaction'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'


tools:
    php_mess_detector:
        config:
            code_size_rules: { cyclomatic_complexity: false, npath_complexity: false }
        filter:
            excluded_paths: ['vendor/*']
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths: ['vendor/*']
    php_code_coverage:
        test_command: vendor/bin/phpunit
        filter:
            excluded_paths: ['vendor/*']
    php_cpd:
        excluded_dirs:
            - tests/generated
        filter:
            excluded_paths: ['vendor/*']
    php_pdepend:
        excluded_dirs:
            1: vendor
            2: tests/generated
    php_loc:
        excluded_dirs:
            - vendor
            - tests/generated
