checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/generated/*'

build:
    environment:
        php:
            version: '7.2'
    dependencies:
        override:
            -
              command: 'yes | pecl install soap'
              not_if: 'php -r "exit(extension_loaded(''soap'') ? 0 : 1);"'
            - 'composer install --dev --no-interaction'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'
