#!/usr/bin/php
<?php

include_once('cli/Cli.php');
include_once('Wsdl2PhpGenerator.php');

$cli = new cli\Cli('wsdl2php', '[-h] [-s] -i wsdlfile -o directory [-n namespace]', '0.1');
$cli->addFlag('-e', 'If all classes should be guarded with if(!class_exists) statements', true, false);
$cli->addFlag('-s', 'If the output should be a single file', true, false);
$cli->addFlag('-i', 'The input wsdl file', false, true);
$cli->addFlag('-o', 'The output directory', false, true);
$cli->addFlag('-n', 'Use namespace with the name', false, false);
$cli->addFlag('--singleElementArrays', 'Adds the option to use single element arrays to the client', true, false);
$cli->addFlag('--xsiArrayType', 'Adds the option to use xsi arrays to the client', true, false);
$cli->addFlag('--waitOneWayCalls', 'Adds the option to use wait one way calls to the client', true, false);
$cli->addFlag('--cacheNone', 'Adds the option to not cache the wsdl to the client', true, false);
$cli->addFlag('--cacheDisk', 'Adds the option to cache the wsdl on disk to the client', true, false);
$cli->addFlag('--cacheMemory', 'Adds the option to cache the wsdl in memory to the client', true, false);
$cli->addFlag('--cacheBoth', 'Adds the option to cache the wsdl in memory and on disk to the client', true, false);
$cli->addFlag('--gzip', 'Adds the option to compress the wsdl with gzip to the client', true, false);
$cli->addFlag('-h', 'Show this help', true, false);

$cli->addAlias('-e', '--classExists');
$cli->addAlias('-e', '--exists');
$cli->addAlias('-s', '--singleFile');
$cli->addAlias('-i', '--input');
$cli->addAlias('-o', '--output');
$cli->addAlias('-n', '--namespace');
$cli->addAlias('-h', '--help');
$cli->addAlias('-h', '--h');

$cli->validate($argv);

$classExists = $cli->getValue('-e');
$singleFile = $cli->getValue('-s');
$inputFile = $cli->getValue('-i');
$outputDir = $cli->getValue('-o');
$namespaceName = $cli->getValue('-n');
$optionsArray = array();
if ($cli->getValue('--singleElementArrays'))
{
  $optionsArray[] = 'SOAP_SINGLE_ELEMENT_ARRAYS';
}
if ($cli->getValue('--xsiArrayType'))
{
  $optionsArray[] = 'SOAP_USE_XSI_ARRAY_TYPE';
}
if ($cli->getValue('--waitOneWayCalls'))
{
  $optionsArray[] = 'SOAP_WAIT_ONE_WAY_CALLS';
}
$wsdlCache = '';
if ($cli->getValue('--cacheNone'))
{
  $wsdlCache = 'WSDL_CACHE_NONE';
}
else if ($cli->getValue('--cacheDisk'))
{
  $wsdlCache = 'WSDL_CACHE_DISK';
}
else if ($cli->getValue('--cacheMemory'))
{
  $wsdlCache = 'WSDL_CACHE_MEMORY';
}
else if ($cli->getValue('--cacheBoth'))
{
  $wsdlCache = 'WSDL_CACHE_BOTH';
}
$gzip = '';
if ($cli->getValue('--gzip'))
{
  $gzip = 'SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP';
}

$config = new Wsdl2Php\Config($inputFile, $outputDir, $singleFile, $classExists, $namespaceName, $optionsArray, $wsdlCache, $gzip);

$generator = new Wsdl2Php\Generator();
$generator->generate($config);