<?php
/**
 * @package wsdl2phpTest
 */

/**
 * Including all needed files
 */
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../Wsdl2PhpValidator.php';

/**
 * Test class for Wsdl2PhpValidator.
 * Generated by PHPUnit on 2009-11-11 at 00:56:02.
 * 
 * @package wsdl2phpTest
 */
class Wsdl2PhpValidatorTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var Wsdl2PhpValidator
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Wsdl2PhpValidator;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * 
   */
  public function testValidateClass()
  {
    $this->assertEquals('foo', $this->object->validateClass('foo'));
    $this->assertEquals('foobar', $this->object->validateClass('foo-bar'));
    $this->assertEquals('Foo', $this->object->validateClass('Foo'));
    $this->assertEquals('foo523', $this->object->validateClass('foo523'));

    $this->setExpectedException('Wsdl2PhpValidationException');
    $this->object->validateClass('SoapClient');

    $this->setExpectedException('Wsdl2PhpValidationException');
    $this->assertEquals('for', $this->object->validateClass('for')); // for is reserved keyword
  }

  /**
   * Testing the validate class function with a reserved keyword
   */
  public function testValidateClassReservedKeyword()
  {
    $this->setExpectedException('Wsdl2PhpValidationException');
    $this->assertEquals('for', $this->object->validateClass('for')); // for is reserved keyword
    $this->assertEquals('List', $this->object->validateClass('List')); // for is reserved keyword
  }

  /**
   * Testing the validate class function with another reserved keyword
   */
  public function testValidateClassReservedKeyword2()
  {
    $this->setExpectedException('Wsdl2PhpValidationException');
    $this->assertEquals('List', $this->object->validateClass('List')); // list is reserved keyword. PHP is not case sensitive in keywords
  }

  /**
   * Test the typename
   */
  public function testValidateType()
  {
    $this->assertEquals('foo', $this->object->validateType('foo'));
    $this->assertEquals('foobar', $this->object->validateType('foo-bar'));
    $this->assertEquals('Foo', $this->object->validateType('Foo'));
    $this->assertEquals('foo523', $this->object->validateType('foo523'));
    $this->assertEquals('array', $this->object->validateType('arrayOf_test'));
    $this->assertEquals('array', $this->object->validateType('arrayOfTest'));
    $this->assertEquals('array', $this->object->validateType('test[]'));
    $this->assertEquals('array', $this->object->validateType('ArrayOf_xsd_int'));

    $this->assertEquals('int', $this->object->validateType('nonNegativeInteger')); 
    $this->assertEquals('float', $this->object->validateType('float'));
    $this->assertEquals('string', $this->object->validateType('normalizedString'));
    $this->assertEquals('array', $this->object->validateType('ArrayOfFoo'));
    $this->assertEquals('array', $this->object->validateType('Foo[]'));

    $this->setExpectedException('Wsdl2PhpValidationException');
    $this->assertEquals('and', $this->object->validateType('and')); // and is reserved keyword
  }

  /**
   * 
   */
  public function testValidateNamingConvention()
  {
    $this->assertEquals('foo', $this->object->validateNamingConvention('foo'));
    $this->assertEquals('foobar', $this->object->validateNamingConvention('foo-bar'));
    $this->assertEquals('Foo', $this->object->validateNamingConvention('Foo'));
    $this->assertEquals('foo523', $this->object->validateNamingConvention('foo523'));
    $this->assertEquals('foo', $this->object->validateNamingConvention('123foo'));
    $this->assertEquals('foo123', $this->object->validateNamingConvention('123foo$123'));
    $this->assertEquals('foo', $this->object->validateNamingConvention('123f|o|o'));
  }
}
?>
